version: '3.8'

services:
  server:
    build: .
    container_name: node-server
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npx", "nodemon", "src/index.js"]